version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: sql_db
    volumes:
    - ./Data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
